version: 2.1
jobs:
  build:
    docker:
      - image: ghcr.io/nlu-final/dockerfile:1.0.0
        auth:
          username: quangtho908
          password: $GHCR_TOKEN
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:kEiE0J85glxA6V3szW+LFuvxaUyZQgvOZoYV3G4cgWU"
      - run:
          name: "Compile with Maven"
          command: mvn clean compile
workflows:
  build_and_deploy:
    jobs:
      - build